export const fooditems = [

    {
        id: 1,
        img: "res1.avif",
        name: "barbeque nation",
        rating: "4.6",
        dishes: "North Indian, BBQ, Kebab, Biryani",
        price: "1,600 for two",
        state: "cantonment, Trichy",
        distance: "3.1km",
        place: "Cantonment",
        location: "Mangalam Towers, Sangiliyandapuram",
        Nation: "Barbeque Nation",
        open: "11am – 11:30pm (Today)",
        phone: "+918069028722",
        address: "Third Floor, Mangalam Towers, Cantonment, Trichy",
        image: "tableimg2.avif",
        image2: "tableimg3.avif",
        image3: "tableimg4.avif",
        Cuisines1: "North indian ",
        Cuisines2: "BBQ",
        Cuisines3: "Kebab",
        Cuisines4: "Biryani",
        Topdishes: "Cajun Potato ",
        Topdishes2: "Deserts",
        Topdishes3: "Kulfi",
        Topdishes4: "PanneerButterMasala",
        Topdishes5: "Starters",
        Topdishes6: "Drinks",
        Image: "foodmenu.avif",
        beverages: "beverages.avif",
        pages1: "3pages",
        pages2: "3pages",
        menuname1: "Food Menu",
        menuname2: "beverages",
        quality: "People Say This Place Is Known For",
        details: "Excellent Experience, Buffet Variety and Quality, Silent Place, Birthday Celebrations, Very Good Quality, Servicing",

        cost: "₹1,600 for two people (approx.) Without alcohol",
        payment: "Cash and Cards accepted",
        info1: "Dinner",
        info2: " Lunch",
        info3: " Home delivery",
        info4: " Serves alcohol ",
        info5: "Indoor seating ",
        info6: "Buffet",

        hlo: [
           
            { id: "4",     orderimage: "order1.avif", orderitem: "Tandoori Chicken Wings (6 Pcs)", des: "Smoky, tender chicken wings coated in mild spices. Juicy, flavourful, and perfect for a quick snack.", price:"100" },
            { id: "5",   orderimage: "order2.avif", orderitem: "Tandoori Tangadi Solo (1 Pc)", des: "Juicy tandoori chicken leg marinated in mild spices and grilled to perfection. Flavourful and satisfying.", price:"250" },
            { id: "6",   orderimage: "order3.avif", orderitem: "Tandoori Egg (2 Nos)", des: "Boiled eggs marinated in tandoori spices and grilled for a smoky, flavourful taste. Light and tasty..", price:"300" },
            { id: "7",   orderimage: "order4.avif", orderitem: "Grilled Paneer Bites (9 Pcs)", des: "Soft, marinated paneer cubes grilled to a light smoky flavour. Tasty, healthy and perfect for snacking", price:"400" }
        ],
        // onlineitem1: "BBQ Bites(Perfect Add-On Bite) (4)",
        // onlineitem2: "Indian Street Food & Chaats (3)",

        // onlineitem3: "Ramadan Special (2)",
        // onlineitem4: "Celebration Barbeque Boxes (2)",
        // onlineitem5: "Barbeque in a Box (Serves 2-3) (2)",
        // title: "BBQ Bites(Perfect Add-On Bite)",
        // firstitem: "Grilled Chicken Bites (9 Pcs)",
        // pieces: "Soft and juicy grilled chicken pieces seasoned with mild spices. Tasty, healthy, and perfect for snacking.",
        // orderimage1: "order1.avif",
        // orderitem1: "Tandoori Chicken Wings (6 Pcs)",
        //  des1:"Smoky, tender chicken wings coated in mild spices. Juicy, flavourful, and perfect for a quick snack.",
        //  orderimage2:"order2.avif",
        // orderitem2: "Tandoori Tangadi Solo (1 Pc)",
        // des2: "Juicy tandoori chicken leg marinated in mild spices and grilled to perfection. Flavourful and satisfying.",
        // orderimage3: "order3.avif",
        // orderitem3: "Tandoori Egg (2 Nos)",
        // des3: "Boiled eggs marinated in tandoori spices and grilled for a smoky, flavourful taste. Light and tasty..",
        // orderimage4: "order4.avif",
        // orderitem4: "Grilled Paneer Bites (9 Pcs)",
        // des4: "Soft, marinated paneer cubes grilled to a light smoky flavour. Tasty, healthy and perfect for snacking",

        // seconditem: " Indian Street Food & Chaats",
        // orderimage5: "order5.webp",
        // orderitem5: "Pani Puri (8 Pcs) (Golgappa)",
        // des5: "Crispy puris filled with spicy, tangy, and refreshing flavored water, mashed potatoes, and chutneys. A perfect burst of flavor in every bite!",

        // orderimage6: "order6.webp",
        // orderitem6: "Raagi Pani Puri (8 Pcs) (Golgappa)",
        // des6: "A healthy twist to the classic! Crispy ragi puris served with spicy, tangy water, mashed potatoes, and chutneys for a wholesome, flavorful treat.",

        // orderimage7: "order7.webp",
        // orderitem7: "Bhel Puri",
        // des7: "A delicious mix of puffed rice, sev, chutneys, onions, and spices. Light, crunchy, and bursting with sweet, spicy, and tangy flavors!",

        // thirditem: " Ramadan Special",
        // orderimage8: "order8.avif",
        // orderitem8: "Iftar Delight Combo - Chicken Biryani & Haleem",
        // des8: "Experience Iftaar bliss: Chicken Biryani + Haleem + Raita & Dates. Tradition on a plate.",

        // orderimage9: "order9.avif",
        // orderitem9: "Iftar Delight Combo - Mutton Biryani & Haleem",
        // des9: "Experience Iftaar bliss: Mutton Biryani + Haleem + Raita & Dates. Tradition on a plate",


        // fouritem: " Celebration Barbeque Boxes",
        // orderimage10: "order10.avif",
        // orderitem10: "Celebration Barbeque In A Box Non Veg",
        // des10: "[Six Starters] Chicken Tikka (4 Pcs) + Reshmi Chicken Wings (6 Pcs) + Fish Tikka (6 Pcs) + Veg Rolls (6 Pcs) + Veg Kebabs (6 Pcs) + Chicken Seekh Kebab (6 Pcs). [Main Course] - Chicken Butter Masala + Egg Curry + Dal Makhani + Chicken Dum Biryani + Whole Wheat Paratha (3 Pcs) [Three Desserts] -  Angoori Gulab Jamun (8Pcs) + Brownie + Moong Dal Halwa [Beverage] - Coke Can (4 Nos). Accompanied with Mint Chutney, Salan, Dips & Salad..",

        // orderimage11: "order11.avif",
        // orderitem11: "Celebration Barbeque In A Box Veg",
        // des11: "[Six Starters] - Tandoori Paneer Tikka (4 Pcs) + Churrasco Pineapple (6 Pcs) + Veg Kebabs (6 Pcs) + Veg Rolls (6 Pcs) + Cheese Triangle (6 Pcs) + Assorted Grilled Corn & Veg (2 Nos) [Main Course] - Paneer Butter Masala + Mix Veg + Dal Makhani + Veg Dum Biryani + Whole Wheat Paratha (3 Nos) [Three Desserts] Angoori Jamun (8 Pcs) + Moong Dal Halwa + Brownie [Beverage] - Coke Can (4 Nos). Accompanied with Mint Chutney, Salan, Dips & Salad. Barbeque Nation buffet served at home.",

        // fiveitem: " Barbeque in a Box (Serves 2-3)",
        // orderimage12: "order12.avif",
        // orderitem12: "Barbeque in a Box (Non Veg) Premium",
        // des12: "[Six Starters] Chicken Tikka (4 Pcs) + Reshmi Chicken Wings (6 Pcs) + Fish Tikka (6 Pcs) + Veg Rolls (6 Pcs) + Veg Kebabs (6 Pcs) + Chicken Seekh Kebab (6 Pcs). [Main Course] - Chicken Butter Masala + Egg Curry + Dal Makhani + Chicken Dum Biryani + Whole Wheat Paratha (3 Pcs) [Three Desserts] - Angoori Gulab Jamun (8Pcs) + Brownie + Moong Dal Halwa. Accompanied with Mint Chutney, Salan, Dips & Salad. Barbeque Nation Buffet served at Home.",

        // orderimage13: "order13.avif",
        // orderitem13: "Barbeque in a Box (Non Veg) Premium (With Prawns and Mutton)",
        // des13: "[Six Starters] - Chilly Garlic Prawns (6 Pcs) + Chicken Tikka (4 Pcs) + Chicken Wings (6 Pcs) + Fish Tikka (6 Pcs) + Veg Kebabs (6 Pcs) + Veg Rolls (6 Pcs) [Main Course] - Butter Chicken + Mutton Rogan Josh + Dal Makhani + Chicken Dum Biryani + Whole Wheat Paratha (3 Nos) [Three Desserts] - Angoori Jamun (8 Pcs) + Moong Dal Halwa + Brownie - Accompanied with Mint Chutney, Salan, Dips & Salad. A premium Barbeque Nation buffet served at home."


    },

    {
        id: 2,
        img: "card2.avif",
        name: "Chinese Wok",
        rating: "4.1",
        dishes: " Chinese",
        price: "200 for two",
        state: "Cantonment, Trichy",
        distance: "2.5km",
        place: "Cantonment",
        Nation: "chinese Wok",
        open: "12midnight – 2am, 11am – 11pm (Today)",
        phone: "+919566439146",
        address: "Building 33, Promenade Road, Cantonment, Trichy",
        image: "tableimg5.avif",
        image2: "tableimg6.avif",
        image3: "tableimg7.avif",
        Cuisines1: "Chinese ",
        Image: "menu.avif",
        pages1: "2pages",
        menuname1: " Menu",
        cost: "₹200 for two people (approx.)",
        info1: "Dinner",
        info2: " Lunch",
        info3: " Home delivery",
        info4: " Indoor seating ",
        // onlineitem1: "Rice & Noodles - Half (4)",
        // onlineitem2: "Rice & Noodles - Full (3)",

        // onlineitem3: "Chinese Bowls (Save upto 40%) (2)",
        // onlineitem4: "Better Deal for 1 Bowl (2)",
        // onlineitem5: "Make Your Own Wok (2)",

        hlo : [
            {id: "8", orderimage: "order14.avif",orderitem: "Veg Chinese Schezwan Fried Rice - Half (500 ml)",des: "A fiery favourite! Rice with veggies in our signature Schezwan sauce — bold, saucy and classic Desi-Chinese. Energy 784.06 (kcal ), Carbohydrate 130.45 gms, Protein 11.67 gms, Fats 22.61gms" , price:"200"},
            {id: "9",  orderimage: "order15.avif",orderitem: "Veg Burnt Garlic Fried Rice - Half (500 ml)",des: "Rice and veggies tossed with aromatic burnt garlic. Smoky, savoury and soul-hugging — Wok magic in every bite. Energy 754.22 (kcal ), Carbohydrate 118.51 gms, Protein 13.48 gms, Fats 23.62gms.", price:"100"},
            {id: "10",  orderimage: "order16.avif", orderitem: "Veg Chilli Garlic Fried Rice - Half (500 ml)",  des: "A spicy, garlicky bomb of a rice bowl. Stir-fried with veggies, chilli flakes and soy — this one means business. Energy 769.28 (kcal ), Carbohydrate 123.22 gms, Protein 13.71 gms, Fats 23.61gms.", price:"400" },
            {id: "11", orderimage: "order17.avif", orderitem: "Veg Chinese Fried Rice - Half (500 ml)", des: "Veggie-loaded rice stir-fried in soy sauce. Clean, simple and delicious — just how you like it. Energy 757.82 (kcal ), Carbohydrate 121.74 gms, Protein 12.49 gms, Fats 23.08gms", price:"300"},
        ],

        // firstitem: "Veg Fried Rice Half",
        // orderimage1: "order14.avif",
        // orderitem1: "Veg Chinese Schezwan Fried Rice - Half (500 ml)",
        // des1: "A fiery favourite! Rice with veggies in our signature Schezwan sauce — bold, saucy and classic Desi-Chinese. Energy 784.06 (kcal ), Carbohydrate 130.45 gms, Protein 11.67 gms, Fats 22.61gms",


        // orderimage2: "order15.avif",
        // orderitem2: "Veg Burnt Garlic Fried Rice - Half (500 ml)",
        // des2: "Rice and veggies tossed with aromatic burnt garlic. Smoky, savoury and soul-hugging — Wok magic in every bite. Energy 754.22 (kcal ), Carbohydrate 118.51 gms, Protein 13.48 gms, Fats 23.62gms.",
        // orderimage3: "order16.avif",
        // orderitem3: "Veg Chilli Garlic Fried Rice - Half (500 ml)",
        // des3: "A spicy, garlicky bomb of a rice bowl. Stir-fried with veggies, chilli flakes and soy — this one means business. Energy 769.28 (kcal ), Carbohydrate 123.22 gms, Protein 13.71 gms, Fats 23.61gms.",

        // orderimage4: "order17.avif",
        // orderitem4: "Veg Chinese Fried Rice - Half (500 ml)",
        // des4: "Veggie-loaded rice stir-fried in soy sauce. Clean, simple and delicious — just how you like it. Energy 757.82 (kcal ), Carbohydrate 121.74 gms, Protein 12.49 gms, Fats 23.08gms",

        // seconditem: " Veg Fried Rice - Full",
        // orderimage5: "order18.avif",
        // orderitem5: "Veg Fried Rice - Full (1000 ml)",
        // des5: "Simple, savoury, and soul-satisfying. Rice tossed with fresh veggies in a light soy seasoning. Everyday favourite, Wok-style. Energy 1005 (kcal ), Carbohydrate 133 gms, Protein 30 gms, Fats 37",

        // orderimage6: "order19.avif",
        // orderitem6: "Veg Burnt Garlic Fried Rice - Full (1000 ml)",
        // des6: "Fragrant rice tossed with crisp veggies and a smoky burnt garlic punch. Finished with fresh coriander. Warning: highly addictive! Energy 1019 (kcal ), Carbohydrate 153gms, Protein 18gms, Fats 35gms",

        // orderimage7: "order20.avif",
        // orderitem7: "Veg Chilli Garlic Fried Rice - Full (1000 ml)",
        // des7: "Rice tossed with veggies, garlic and fiery chilli flakes in a bold soy base. Smoky, spicy, and Wok-tossed to perfection. Energy 1040 (kcal), Carbohydrate 160 gms, Protein 24 gms, Fats 43",

        // thirditem: " Veg Bowl",
        // orderimage8: "order21.webp",
        // orderitem8: "Chilli Paneer Bowl",
        // des8: "[650 ml] The OG of Desi-Chinese! Paneer cubes with onion and capsicum in our signature spicy chilli sauce. Served with rice or noodles. Its got swag and sizzle. Energy 279.15 (kcal), Carbohydrate 21.02 gms, Protein 11.47 gms, Fats 16.11gms",

        // orderimage9: "order22.avif",
        // orderitem9: "Veg Manchurian Lite Bowl",
        // des9: "Crispy veggie balls wok-tossed with onion and capsicum in our classic peppery Manchurian sauce. Full on flavour, light on spice. Served with rice or noodles.",

        // fouritem: "Better Deal for 1 Bowl - Veg",
        // orderimage10: "order23.avif",
        // orderitem10: "Veg Schezwan Noodles - Half (500 ml).",
        // des10: "  Schezwan’s in the building — spicy, saucy, desi Chinese-style! Veggies, noodles, wok-tossed in our fiery schezwan sauce. Energy 511.51 (kcal ), Carbohydrate 81.22 gms, Protein 10.335 gms, Fats 20.26gms",

        // orderimage11: "order24.avif",
        // orderitem11: "Veg Chinese Hakka Noodles - Half (500 ml).",
        // des11: "No-frills. All flavour. The OG Indo-Chinese classic — tossed with veggies, a touch of dark soya, and that wok-charred aroma you love. Energy 731.17 (kcal ), Carbohydrate 115.94 gms, Protein 16.5 gms, Fats 28.55gms",

        // fiveitem: " Make Your Own Wok - Veg",
        // orderimage12: "order25.avif",
        // orderitem12: "Veg Personal Wok Bowl",
        // des12: "For the light eaters and customizers! Choose your base, sauce, 4 crunchy veggies, 2 seasonings — and make your wok your way.",

        // orderimage13: "order26.avif",
        // orderitem13: "Veg Medium Wok Bowl",
        // des13: "Bigger bowl, bigger choices! Rice or noodles, your sauce, 6 veggies, 2 seasonings — your desi Chinese masterpiece starts here."



    },
    {
        id: 3,
        img: "card3.avif",
        name: "Trichy Kitchen",
        rating: "3.2",
        dishes: "South Indian, North Indian",
        price: "1,400 for two",
        state: "cantonment, Trichy",
        distance: "3.1km",
        place: "Cantonment",
        Nation: "Trichy Kitchen",
        open: "6:30am – 11pm (Today)",
        phone: "+918925805605",
        address: "Collectors Office Road, Cantonment, Trichy",
        image: "tableimg8.avif",
        image2: "tableimg9.avif",
        image3: "tableimg10.avif",
        Cuisines1: " South Indian",
        Cuisines2: "North Indian",
        Image: "special menu.avif",
        beverages: "food menu 2.avif",
        pages1: "1pages",
        pages2: "20pages",
        menuname1: "Special Menu",
        menuname2: "Food menu",
        cost: "₹1400 for two people (approx.)",
        digital: "Digital payments accepted",
        payment: "Cash and Cards accepted",
        info1: "lunch",
        info2: " Dinner",
        info3: " Breakfast",
        info4: " Takeaway available ",
        info5: "Outdoor seating ",
        info6: "Indoor seating",
    },

    {
        id: 4,
        img: "card4.avif",
        name: "Sharief Bhai Biryani",
        rating: "4.1",
        dishes: "Briyani shawarma,Kebab, Arabian, Rolls,Tea,Deserts,Beverages  ",
        price: "700 for two",
        state: "Woraiyur, Trichy",
        distance: "4.7km",
        place: "woraiyur",
        Nation: "Sharief Bhai Biryani",
        open: "11:30am – 11:30pm (Today)",
        phone: "+9184380470",
        address: "3/1, 1st Floor, Ward 56, Annamalai Nagar, Woraiyur, Trichy",
        image: "tableimg11.avif",
        image2: "tableimg12.avif",
        image3: "tableimg13.jpg",
        Cuisines1: "Briyani ",
        Cuisines2: "shawarma",
        Cuisines3: "Kebab",
        Cuisines4: "Arabian",
        Cuisines5: "Rolls ",
        Cuisines6: "tea",
        Cuisines7: "Desserts",
        Cuisines8: "beverages",
        Image: "food menu 3.avif",
        beverages: "beverages2.avif",
        pages1: "15pages",
        pages2: "1pages",
        menuname1: "Food Menu",
        menuname2: "beverages",
        cost: "₹700 for two people (approx.)",
        digital: "Digital payments accepted",
        info1: "Lunch",
        info2: " Dinner",
        info3: " Home delivery",
        info4: " Takeaway available",
        onlineitem1: "Ramzan Specials  (4)",
        onlineitem2: "Hyderabadi Dum Biryani (Newly Launched)  (3)",

        onlineitem3: "Biryani - Dakhni Style  (2)",
        onlineitem4: "Party Combo Meals (2)",
        onlineitem5: "Starters  (2)",
        hlo : [ 
            {  id:"12", Name:"Sharief Bhai Biryani",Address:"3/1, 1st Floor, Ward 56, Annamalai Nagar, Woraiyur," , orderimage: "order27.avif", orderitem: "All day Ramzan Combo (Chicken) (Serves 1)", des: "Combo Consists of Onion Samosa-1 Nos, Chicken Kheema Samosa-1 Nos, Chicken Sheek-1 Nos, Chicken Biryani with one Piece of Chicken, Chicken Haleem, Gulab Jamun-1 No, Raita And Mint Chutney , packed in an 8 compartment meal tray.(Serve 1). Our exclusive ramadan offering! Energy(Kcal) : 1734.22, Protein(g) : 64.29, Carbs(g) : 94.34, Fat(g) : 123.24, Fibre(g) : 10.34, Sugars (g) : 30.95, Sodium (mg) : 3322.98", price:"200"},
             { id:"13",orderimage: "order28.avif", orderitem: "Mutton Iftar Box (Serves 3)", des: "Consists of A Large Portion of Mutton Dum Biryani, Mutton Haleem, Chicken 65-Boneless, 3 Mutton Kheema Samosa, 3 Onion Samosa, 3 Rose Sharbath, 4 Gulab Jamun, 4 Dates, and 2 Water Bottle.( Serves 3). Our exclusive Ramadan offering!",price:"100" } ,
             { id:"14", orderimage: "order29.avif",  orderitem: "Mutton Mini Iftar Box", des: "Celebrate the spirit of Ramzan with Mutton Egg Kheema Roti, Mutton Haleem -100grams, 2 Onion Samosa, Dates, Water Bottle -1" , price:"400"},
             {id:"15",orderimage: "order30.avif", orderitem: "Chicken Iftar Box (Serves 3)", des: "Combo Consists of Large Portion of Chicken Biryani, Chicken Haleem, Chicken 65- B/L, chicken kheema samosa 3 Nos, Onion Samosa 3 Nos, Rose Sharbath -300ml (2Nos), Gulab Jamun-6 Nos and Water Bottle 2nos ( Serves 3 )Our exclusive Ramadan offering!", price:"300"},
        // orderimage4: "order30.avif", }
        ]
        // firstitem: "Ramzan Specials",
        // orderimage1: "order27.avif",
        // orderitem1: "All day Ramzan Combo (Chicken) (Serves 1)",
        // des1: "Combo Consists of Onion Samosa-1 Nos, Chicken Kheema Samosa-1 Nos, Chicken Sheek-1 Nos, Chicken Biryani with one Piece of Chicken, Chicken Haleem, Gulab Jamun-1 No, Raita And Mint Chutney , packed in an 8 compartment meal tray.(Serve 1). Our exclusive ramadan offering! Energy(Kcal) : 1734.22, Protein(g) : 64.29, Carbs(g) : 94.34, Fat(g) : 123.24, Fibre(g) : 10.34, Sugars (g) : 30.95, Sodium (mg) : 3322.98",
        // orderimage2: "order28.avif",
        // orderitem2: "Mutton Iftar Box (Serves 3)",
        // des2: "Consists of A Large Portion of Mutton Dum Biryani, Mutton Haleem, Chicken 65-Boneless, 3 Mutton Kheema Samosa, 3 Onion Samosa, 3 Rose Sharbath, 4 Gulab Jamun, 4 Dates, and 2 Water Bottle.( Serves 3). Our exclusive Ramadan offering!",
        // orderimage3: "order29.avif",
        // orderitem3: "Mutton Mini Iftar Box",
        // des3: "Celebrate the spirit of Ramzan with Mutton Egg Kheema Roti, Mutton Haleem -100grams, 2 Onion Samosa, Dates, Water Bottle -1",
        // orderimage4: "order30.avif",
        // orderitem4: "Chicken Iftar Box (Serves 3)",
        // des4: "Combo Consists of Large Portion of Chicken Biryani, Chicken Haleem, Chicken 65- B/L, chicken kheema samosa 3 Nos, Onion Samosa 3 Nos, Rose Sharbath -300ml (2Nos), Gulab Jamun-6 Nos and Water Bottle 2nos ( Serves 3 )Our exclusive Ramadan offering!",
        // seconditem: " Hyderabadi Dum Biryani (Bucket)",
        // orderimage5: "order31.avif",
        // orderitem5: "Mutton Hyderabadi Bucket Biryani",
        // des5: "Slow-cooked Hyderabadi mutton biryani with tender meat and rich masala, layered with fragrant basmati rice. Served with 12 pieces of mutton, 10 pieces of chicken kebab (with bone), and 6 boiled eggs.raitha & salan",

        // orderimage6: "order32.avif",
        // orderitem6: "Chicken Hyderabadi Bucket Biryani",
        // des6: "A Royal Bucket of aromatic Hyderabadi chicken biryani made with long-grain basmati rice and rich spices. Served with 12 pieces of chicken, 10 pieces of chicken kebab (with bone), and 6 boiled eggs, raitha & salan",

        // orderimage7: "order33.avif",
        // orderitem7: "Mutton Kheema Hyderabadi Bucket Biryani",
        // des7: "Classic Hyderabadi biryani made with spiced mutton kheema and aromatic rice. with 10 pieces of chicken kebab (with bone), and 6 boiled eggs.raitha & salan",


        // thirditem: " Non Veg Biryani",
        // orderimage8: "order34.avif",
        // orderitem8: "Chicken 65 Boneless Biryani",
        // des8: "Dum cooked traditional zeerak samba rice with rich flavours and topped with 8-10 small size boneless chunks of chicken kebab, prepared with our home made special masala, served with raitha & salan. Experience the flavours of Dakhni Biryani, a very fresh alternate to the Mandi biryani. Energy (kcal ) : 1114, Protein (g) : 47, Fat (g) : 35, Dietary fibre (gm) : 11, carbohydrates(g) : 144, Allergen : Dairy,.",

        // orderimage9: "order35.avif",
        // orderitem9: "Mutton Biryani (Har-dil-Azeez Gosht)",
        // des9: "Traditional dum-cooked Zeerak Samba rice layered with 3 pieces of tender lamb meat, slow-cooked in rich Dakhni spices — just like in a true Muslim household. Experience the soulful flavors of authentic Dakhni Biryani — a fresh and aromatic alternative to the Mandi style. Energy (kcal ) : 1408, Protein (g) : 41, Fat (g) : 78, Dietary fibre (gm) : 8, carbohydrates(g) : 131, Allergen : Dairy",


        // fouritem: " Party Combo Meals",
        // orderimage10: "order36.avif",
        // orderitem10: "Friday Bhai Day - Chicken Biryani Combo",
        // des10: "Combo consists of Chicken Dum Biryani (2 Portions), Chicken starter (Small) and matka phirni (small) 2 units. (Serves 2) Energy(Kcal) : 4985.82, Protein(g) : 275.14, Carbs(g) : 301.96, Fat(g) : 295.14, Fibre(g) : 18.92, Sugars (g) : 88.5, Sodium (mg) : 11713.99",
        // orderimage11: "order37.avif",
        // orderitem11: "Friday Bhai Day - Veg Biryani Combo",
        // des11: "Combo consists of Soya Chaap Biryani (2 Portions), Paneer 65 (Small) and matka phirni (small) 2 nos. ( Serves 2 ) Energy(Kcal) : 3344.1, Protein(g) : 84.74, Carbs(g) : 275.47, Fat(g) : 218.66, Fibre(g) : 23.6, Sugars (g) : 95.48, Sodium (mg) : 11828.19",

        // fiveitem: " Starters",
        // orderimage12: "order38.avif",
        // orderitem12: "Chicken 65 - Boneless",
        // des12: " Crisp and tender boneless chicken bites are deep fried with a special batter. 9 pieces per serving. Energy (kcal ) : 431, Protein (g) : 31, Fat (g) : 28, Dietary fibre (gm) : 3, carbohydrates(g) : 09, Allergen : Dairy, Vinegar.",

        // orderimage13: "order39.avif",
        // orderitem13: "Chicken Tikka",
        // des13: "Tender chicken cubes Marinated in Yogurt cooked in tandoor along with red Chilly and special masala . 5 peices per serving. Energy(Kcal) : 528.52, Protein(g) : 62.23, Carbs(g) : 15.46, Fat(g) : 23.43, Fibre(g) : 3.81, Sugars (g) : 3.83, Sodium (mg) : 304.76,",
    },
    {
        id: 5,
        img: "card5.avif",
        name: "KMS Hakkim",
        rating: "4.5",
        dishes: " Briyani,Ice cream ",
        price: "700 for two",
        state: "thillai Nagar, Trichy",
        distance: "4.4km",
        place: "Thillai nagar",
        Nation: "KMS Hakkim",
        open: "11am – 11pm (Today)",
        phone: "+911723819909",
        address: "5, Near Passport Office, Sastri Road, North East Extension, Thillai Nagar, Trichy",
        image: "tableimg14.avif",
        image2: "tableimg15.avif",
        image3: "tableimg16.avif",
        Cuisines1: "Briyani ",
        Cuisines2: "Ice cream",
        Image: "foodmenu4.avif",
        beverages: "beverages3.avif",
        pages1: "5pages",
        pages2: "1pages",
        menuname1: "Food Menu",
        menuname2: "beverages",
        cost: "₹700 for two people (approx.)",
        quality: "People Say This Place Is Known For",
        details: "Excellent Experience, Buffet Variety and Quality, Silent Place, Birthday Celebrations, Very Good Quality, Servicing",
        payment: "Cash and Cards accepted",
        info1: "Dinner",
        info2: " Lunch",
        info3: " Home delivery",
        info4: " Takeaway available",
        info5: "Indoor seating",
        onlineitem1: "Rice  (4)",
        onlineitem2: "Starters (3)",

        onlineitem3: "Family Pack  (2)",
        onlineitem4: "Main Course  (2)",
        onlineitem5: "friedRice   (2)",
         hlo : [ 
            {id:"16",Name:"KMS Hakkim",Address:"5, Near Passport Office, Sastri Road, North East Extension, Thillai Nagar," , orderimage: "order40.avif",  orderitem: "Plain Biryani",  des: "Mild flavoured aromatic rice. Best accompanied with various onion, tomato based gravies.",price:"250"  },
            {id:"17",   orderimage: "order41.avif",   orderitem: "Egg Masala [2 Eggs]", des: "Egg gravy is a North Indian dish of hard boiled eggs simmered in a spicy and super aromatic onion tomato masala.",price:"100" },
            {id:"18", orderimage: "order42.avif",  orderitem: "Veg Pulao", price:"150" },
            {id:"19", orderimage: "order43.avif",  orderitem: "Mushroom Pulao", price:"300"  }
         ]
        // firstitem: "Rice",
        // orderimage1: "order40.avif",
        // orderitem1: "Plain Biryani",
        // des1: "Mild flavoured aromatic rice. Best accompanied with various onion, tomato based gravies.",
        // orderimage2: "order41.avif",
        // orderitem2: "Egg Masala [2 Eggs]",
        // des2: "Egg gravy is a North Indian dish of hard boiled eggs simmered in a spicy and super aromatic onion tomato masala.",
        // orderimage3: "order42.webp",
        // orderitem3: "Veg Pulao",

        // orderimage4: "order43.jpg",
        // orderitem4: "Mushroom Pulao",

        // seconditem: " Starters",
        // orderimage5: "order44.avif",
        // orderitem5: "Chicken 65",
        // des5: "Cottage cheese dumpling stuffed served in cashew nut gravy.",

        // orderimage6: "order45.avif",
        // orderitem6: "Chicken Lollipop",
        // des6: "Perfectly marinated, crispy on the outside and tender on the inside our chicken lollipop are an irresistible snack or appetizer that is hard to put down.",

        // orderimage7: "order46.avif",
        // orderitem7: "Chilli Chicken",

        // thirditem: " Family Pack",
        // orderimage8: "order47.jpg",
        // orderitem8: "Chicken biryani [half]",


        // orderimage9: "order35.avif",
        // orderitem9: "Mutton Biryani [5 Serves]",

        // fouritem: " Mix Veg Curry",
        // orderimage10: "order48.avif",
        // orderitem10: "Paneer Butter Masala",
        // orderimage11: "order49.jpg",
        // orderitem11: "Mushroom Masala",
        // fiveitem: " Veg Noodles",
        // orderimage12: "order50.avif",
        // orderitem12: "Schezwan Veg Noodles",

        // orderimage13: "order51.jpg",
        // orderitem13: "Egg Noodles",
    },

    {
        id: 6,
        img: "card6.avif",
        name: "Suvai Briyani Family Restraurant",
        rating: "4.2",
        dishes: "Briyani",
        price: "300 for two",
        state: "Karumandapam, Trichy",
        distance: "4km",
        place: "karumandapam",
        Nation: "Suvai Briyani Family Restaurant",
        open: "11am – 11pm (Today)",
        phone: "+916687899989",
        address: "73/2, Karumandapam, Trichy",
        image: "tableimg17.avif",
        image2: "tableimg18.avif",
        image3: "tableimg19.jpg",
        Cuisines1: "Briyani ",
        pages1: "10pages",
        menuname1: "Food Menu",
        Image: "foodmenu5.avif",
        cost: "₹300 for two people (approx.)",
        quality: "People Say This Place Is Known For",
        details: "Excellent Experience, Buffet Variety and Quality, Silent Place, Birthday Celebrations, Very Good Quality, Servicing",
        payment: "Cash and Cards accepted",
        digital: "Digital payments accepted",
        info1: "Lunch",
        info2: " Dinner",
        info3: " Home delivery",
        info4: " Takeaway available",
        info5: "Indoor seating",
        info6: "Free parking",
        onlineitem1: "Briyani (3)",
        hlo:[
            {id:"20", Name:"Suvai Briyani Family Restraurant", Adress:"73/2, Karumandapam,", orderimage: "order52.avif",  orderitem: "Chicken Empty Biryani", des: "Biryani served with boiled egg, onion raita and brinjal gravy. seeraga samba rice  ,bullet rice (packed in 500ml box+raita+dalcha)", price:"200" },
            { id:"21", orderimage: "order53.avif", orderitem: "Chicken Biryani", des: "Biryani served with boiled egg, onion raita and brinjal gravy. 2piese 1egg seeraga samba and bullet rice (packed in 500ml box+raita+dalcha+pieces 1+1egg)" , price:"100"  },
            { id:"22", orderimage: "order54.avif", orderitem: "Mutton Biryani",  des: "Seeraga samba mutton biryani served with mutton pieces, onion raita and brinjal gravy.", price:"250"  },
        ]
        // firstitem: "Biryani",
        // orderimage1: "order52.avif",
        // orderitem1: "Chicken Empty Biryani",
        // des1: "Biryani served with boiled egg, onion raita and brinjal gravy. seeraga samba rice  ,bullet rice (packed in 500ml box+raita+dalcha)",
        // orderimage2: "order53.avif",
        // orderitem2: "Chicken Biryani",
        // des2: "Biryani served with boiled egg, onion raita and brinjal gravy. 2piese 1egg seeraga samba and bullet rice (packed in 500ml box+raita+dalcha+pieces 1+1egg)",
        // orderimage3: "order54.avif",
        // orderitem3: "Mutton Biryani",
        // des3: "Seeraga samba mutton biryani served with mutton pieces, onion raita and brinjal gravy."
    },
    {
        id: 7,
        img: "card7.avif",
        name: "Thomboora Restaurant",
        rating: "3.6",
        dishes: "North Indian, Pizza, Pasta, Biryani, Chinese, Continental, Desserts, Beverages",
        price: "1,500 for two",
        state: "Main Guard Gate, Trichy",
        distance: "4.3km",
        place: "Main Guard Gate",
        Nation: "Thamboora Restaurant",
        open: "11:45am – 3:45pm, 6:45pm – 10:45pm (Today)",
        phone: "+912345345632",
        address: "C 27, North East Extension, Fort Station Road, Main Guard Gate, Trichy",
        image: "tableimg20.avif",
        image2: "tableimg21.avif",
        image3: "tableimg22.avif",
        Cuisines1: "North indian ",
        Cuisines2: "Pizza",
        Cuisines3: "Pasta",
        Cuisines4: "biryani",
        Cuisines5: "Chinese",
        Cuisines6: "continental",
        Cuisines7: "Biryani",
        Cuisines8: "Beverages",
        Image: "beverages4.avif",
        beverages: "deliverymenu.avif",
        thirdpart: "foodmenu6.avif",

        pages1: "1pages",
        pages2: "1pages",
        pages3: "17pages",
        menuname1: "Beverages",
        menuname2: "Delivery Menu",
        menuname3: "Food Menu",
        cost: "₹1,500 for two people (approx.)",
        digital: "Digital payments accepted",
        info1: "Lunch",
        info2: " Dinner",
        info3: " Takeaway available",
        onlineitem1: "Soups  (4)",
        onlineitem2: "Tandoor Starters (3)",

        onlineitem3: "Oriental Starters (2)",
        onlineitem4: "Specilty Sizzlers  (2)",
        onlineitem5: "Special Roti & Rolls  (2)",
        hlo:[
            {id:"23", Name:"Thomboora Restaurant", Adress:"C 27, North East Extension, Fort Station Road, Main Guard Gate,",orderimage: "order55.avif", orderitem: "Chicken Burned Garlic Soup", des: "Chicken Soup With Fried Garlic.", price:"250"},
            {id:"24",  orderimage: "order56.jpg", orderitem: "Chicken Cracking Soup", des: "Chef'S Special Soup Topped With Cracking Rice" ,price:"400"},
            {id:"25", orderimage: "order57.jpg", orderitem: "Chicken Manchow Soup",des: "Chicken Soup With Fried Noodles" , price:"350"},
            {id:"26", orderimage:"order58.jpg", orderitem: "Chicken Sichuan Hot & Sour Soup",  des: "Spiced Soup With Mushroom And Chicken" ,price:"100" }

        ],
        // firstitem: "Soups",
        // orderimage1: "order55.jpg",
        // orderitem1: "Chicken Burned Garlic Soup",
        // des1: "Chicken Soup With Fried Garlic.",
        // orderimage2: "order56.jpg",
        // orderitem2: "Chicken Cracking Soup",
        // des2: "Chef'S Special Soup Topped With Cracking Rice",
        // orderimage3: "order57.jpg",
        // orderitem3: "Chicken Manchow Soup",
        // des3: "Chicken Soup With Fried Noodles",
        // orderimage4: "order58.jpg",
        // orderitem4: "Chicken Sichuan Hot & Sour Soup",
        // des4: "Spiced Soup With Mushroom And Chicken",
        // seconditem: " Tandoori Chicken",
        // orderimage5: "order59.avif",
        // orderitem5: "Chicken Hariyali Tikka",
        // des5: "Tender Chicken Marinated in Spiced Mint and Coriander Cooked in Tandoor",
        // orderimage6: "order60.jpg",
        // orderitem6: "Chicken Lapeta Kebab",
        // des6: "Breast Of Chicken Rolled In Mushroom And Cheese Stuffing Marinated In Green Herbs",

        // orderimage7: "order61.jpg",
        // orderitem7: "Chicken Patiala [2 Leg Pieces]",
        // des7: "Black Pepper Crusted, Cardamom Flavoured Mild Creamy Spiced Chicken Breast",
        // thirditem: " Oriental Starters",
        // orderimage8: "order62.jpg",
        // orderitem8: "BBQ Wings",
        // des8: "Marinated chicken wings deep fried and tossed in BBQ sauce.",

        // orderimage9: "order63.jpg",
        // orderitem9: "Butter Garlic Chicken",
        // des9: "Chinese Style Tossed In Butter Garlic Sauce",
        // fouritem: " Specilty Sizzlers",
        // orderimage10: "order65.jpg",
        // orderitem10: "Chicken Oriental Sizzler",
        // des10: "Tender Chicken And Vegetables Tossed In Chinese Brown Sauce Egg Fried Rice Fries Gravy And Chicken Drumstick",
        // orderimage11: "order64.jpg",
        // orderitem11: "Tandoori Chicken Overload Sizzler",
        // des11: "A Combination Of Assorted Chicken Kebab Served On Bed Of Jeera Coariander Rice Special Tomato Gravy Fries And Pakoda",
        // fiveitem: " Special Roti & Rolls",
        // orderimage12: "order66.avif",
        // orderitem12: "Chicken Baida Roti",
        // des12: "An Awadhi Street food made with Roomali Roti, spiced chicken mince herbs and bitten eggs.",

        // orderimage13: "order67.avif",
        // orderitem13: "Mutton Baida Roti",
        // des13: "An Awadhi Street food made with Roomali roti, spiced mutton mince, herbs and bitten eggs."




    },
    {
        id: 8,
        img: "card8.avif",
        name: "Grill Chicken",
        rating: "4.0",
        dishes: " Arabian, Chinese, BBQ, Rolls, Shake, Mughlai, Kerala",
        price: "500 for two",
        state: "Thilai Nagar, Trichy",
        distance: "4.6km",
        place: "Thillai Nagar",
        Nation: "Grill Chicken",
        open: "12noon – 10:30pm (Today)",
        phone: "+918769872345",
        address: "10, First Cross, Thillai Nagar, Trichy",
        image: "tableimg23.avif",
        image2: "tableimg24.avif",
        image3: "tableimg25.avif",
        Cuisines1: "Arabian ",
        Cuisines2: "Chinese",
        Cuisines3: "BBQ",
        Cuisines4: "Rolls",
        Cuisines5: "Shake",
        Cuisines6: "Mughlai",
        Cuisines7: "Kerala",
        pages1: "5pages",
        menuname1: "menu",
        Image: "menu2.avif",
        cost: "₹500 for two people (approx.)",
        quality: "People Say This Place Is Known For",
        details: "Excellent Experience, Buffet Variety and Quality, Silent Place, Birthday Celebrations, Very Good Quality, Servicing",
        payment: "Cash and Cards accepted",
        digital: "Digital payments accepted",
        info1: "Dinner",
        info2: " Lunch",
        info3: " Takeaway available",
        info4: "Free parking",
        onlineitem1: "Veg Soup  (4)",
        onlineitem2: "Non Veg Soup(3)",

        onlineitem3: "Veg Starter (2)",
        onlineitem4: "Non Veg Starter (2)",
        onlineitem5: "Salad & Raita (2)",
        hlo:[
            {id:"27", Name:"Grill Chicken", Adress:"10, First Cross, Thillai Nagar," , orderimage: "order68.jpg",orderitem: "Clear Soup Veg", price:"100"},
            {id:"28", orderimage: "order69.jpg",orderitem: "Cream Of Mushroom Soup", price:"200" },
            {id:"29", orderimage: "order70.jpg",orderitem: "Cream Of Tomato Soup", price:"399"},
            {id:"30", orderimage: "order71.jpg", orderitem: "Hot & Sour Veg Soup" ,price:"100" },


        ],
        // firstitem: "Veg Soup",
        // orderimage1: "order68.jpg",
        // orderitem1: "Clear Soup Veg",


        // orderimage2: "order69.jpg",
        // orderitem2: "Cream Of Mushroom Soup",
        // orderimage3: "order70.jpg",
        // orderitem3: "Cream Of Tomato Soup",

        // orderimage4: "order71.jpg",
        // orderitem4: "Hot & Sour Veg Soup",
        // seconditem: " Non Veg Soup",
        // orderimage5: "order72.avif",
        // orderitem5: "Chicken Clear Soup",
        // des5: "A delightfully flavor-packed clear soup with chopped veggies and chicken pieces - perfect to satiate your cravings.",

        // orderimage6: "order73.avif",
        // orderitem6: "Cream Of Chicken Soup",
        // des6: "A creamy soup made from juicy chicken",
        // orderimage7: "order74.jpg",
        // orderitem7: "Hot & sour Chicken Soup",
        // thirditem: " Veg Starter",
        // orderimage8: "order75.avif",
        // orderitem8: "Mushroom 65",
        // des8: "A delightfully tasty dish with tender mushrooms coated in spicy sauces, assorted spices and tossed with veggies.",
        // orderimage9: "order76.avif",
        // orderitem9: "Baby Corn 65",
        // fouritem: "Non Veg Starter",
        // orderimage10: "order77.jpg",
        // orderitem10: "Mutton Sukka",
        // orderimage11: "order78.jpg",
        // orderitem11: "Crispy Chicken",
        // fiveitem: " Salad & Raita",
        // orderimage12: "order79.jpg",
        // orderitem12: "Arabian Salata",

        // orderimage13: "order80.jpg",
        // orderitem13: "Arabic Salad Non Veg",
    },
    {
        id: 9,
        img: "card9.avif",
        name: "Kanchana Kari Virunthu Restaurant",
        rating: "4.2",
        dishes: "South Indian, North Indian, Chinese, Chettinad, Fast Food",
        price: "1,400 for two",
        state: "cantonment, Trichy",
        distance: "2.7km",
        place: "cantonment",
        Nation: "Kanchana Kari Virunthu Restaurant",
        open: "11am – 11pm (Today)",
        phone: "+918434893241",
        address: "99, Shop 16 & 17, Sangillyandapuram, Tiruchirappalli, Williams Road, Cantonment, Trichy",
        image: "tableimg26.jpg",
        image2: "tableimg27.avif",
        image3: "tableimg28.avif",
        Cuisines1: "South Indian ",
        Cuisines2: "North Indian",
        Cuisines3: "Chinese",
        Cuisines4: "Chettinad",
        Cuisines5: "Fast Food",
        pages1: "9pages",
        menuname1: " Food Menu",
        Image: "foodmenu7.avif",
        cost: "₹650 for two people (approx.)",
        quality: "People Say This Place Is Known For",
        details: "Excellent Experience, Buffet Variety and Quality, Silent Place, Birthday Celebrations, Very Good Quality, Servicing",
        payment: "Cash and Cards accepted",
        digital: "Digital payments accepted",


        info1: "Dinner",
        info2: " Lunch",
        info3: " Home delivery",
        info4: "Takeaway available",
        info5: "Indoor seating",
        onlineitem1: "Soups Veg (4)",
        onlineitem2: "Soups Non - Veg (2)",

        onlineitem3: "Starters (2)",
        onlineitem4: "Tandoori / Bbq  (2)",
        onlineitem5: "Meals (2)",
        hlo:[
            {id:"31", Name:"Kanchana Kari Virunthu Restaurant", Address:"99, Shop 16 & 17, Sangillyandapuram, Tiruchirappalli, Williams Road, Cantonment," ,orderimage: "order81.avif",orderitem: "Veg Clear Soup", price:"100" },
            {id:"32", orderimage: "order82.avif",orderitem: "Hot & Sour Veg Soup", price:"300" },
            {id:"33",  orderimage: "order83.jpg",orderitem: "Sweet Corn Veg Soup", price:"400" },
            {id:"34", orderimage: "order84.jpg",orderitem: "Mushroom Soup",  price:"100"},


        ],
        // firstitem: "Soups Veg",
        // orderimage1: "order81.avif",
        // orderitem1: "Veg Clear Soup",


        // orderimage2: "order82.avif",
        // orderitem2: "Hot & Sour Veg Soup",
        // orderimage3: "order83.jpg",
        // orderitem3: "Sweet Corn Veg Soup",

        // orderimage4: "order84.jpg",
        // orderitem4: "Mushroom Soup",

        // seconditem: " Soups Non - Veg",
        // orderimage5: "order85.jpg",
        // orderitem5: "Hot & Sour Chicken Soup",

        // orderimage6: "order86.jpg",
        // orderitem6: "Chicken Clear Soup",

        // thirditem: "Starters",
        // orderimage8: "order87.jpg",
        // orderitem8: "Gobi 65",


        // orderimage9: "order88.jpg",
        // orderitem9: "Mushroom 65",
        // fouritem: "Tandoori / Bbq",
        // orderimage10: "order89.avif",
        // orderitem10: "Tandoori",
        // des10: "  Tandoor cooked chicken chunks marinated in a yogurt and chilli based masala",
        // orderimage11: "order90.avif",
        // orderitem11: "Bbq",
        // fiveitem: "Meals",
        // orderimage12: "order91.avif",
        // orderitem12: "Veg Meals",
        // des12: "( Rice, Kootu, Poriyal, Keerai, Sambar, Kara / Morr Kulambu, Rasam, Butter Milk, Appalam, Pickle, Kesari )",

        // orderimage13: "order92.avif",
        // orderitem13: "Non Veg Meal",
        // des13: "( Rice, Kootu, Poriyal, Keerai, Boiled Egg, Mutton, Chicken, Fish Gravy, Rasam, Butter Milk, Pickle, Kesari )"

    }











]